//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiSql.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HiSql.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 [{&quot;MinVersion&quot;:&quot;1.0.0.1&quot;,&quot;MaxVersion&quot;:&quot;1.0.4.7&quot;,&quot;UpgradTabs&quot;:[{&quot;TabName&quot;:&quot;Hi_Domain&quot;,&quot;Columns&quot;:[{&quot;TabFieldAction&quot;:2,&quot;ColumnInfo&quot;:{&quot;DbServer&quot;:&quot;&quot;,&quot;DbName&quot;:&quot;&quot;,&quot;TabName&quot;:&quot;Hi_Domain&quot;,&quot;FieldName&quot;:&quot;Domain&quot;,&quot;ReFieldName&quot;:&quot;Domain&quot;,&quot;FieldType&quot;:11,&quot;DBDefault&quot;:10,&quot;SortNum&quot;:5,&quot;FieldDesc&quot;:&quot;数据域名&quot;,&quot;FieldLen&quot;:20,&quot;FieldDec&quot;:0,&quot;SNO&quot;:&quot;&quot;,&quot;SNO_NUM&quot;:&quot;&quot;,&quot;Regex&quot;:&quot;&quot;,&quot;IsPrimary&quot;:true,&quot;IsIdentity&quot;:false,&quot;IsNull&quot;:false,&quot;IsBllKey&quot;:true,&quot;IsIgnore&quot;:false,&quot;IsRequire&quot;:true,&quot;IsObsolete&quot;:false,&quot;IsSys&quot;:true,&quot;DefaultValue&quot;:&quot;&quot;,&quot;IsShow&quot;:true,&quot;IsS [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UpgradeVersion {
            get {
                return ResourceManager.GetString("UpgradeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{&quot;MinVersion&quot;:&quot;1.0.4.7&quot;,&quot;MaxVersion&quot;:&quot;1.0.5.5&quot;,&quot;UpgradTabs&quot;:[{&quot;TabName&quot;:&quot;Hi_TabModel&quot;,&quot;Columns&quot;:[{&quot;TabFieldAction&quot;:2,&quot;ColumnInfo&quot;:{&quot;DbServer&quot;:&quot;&quot;,&quot;DbName&quot;:&quot;&quot;,&quot;TabName&quot;:&quot;Hi_TabModel&quot;,&quot;FieldName&quot;:&quot;TabName&quot;,&quot;ReFieldName&quot;:&quot;TabName&quot;,&quot;FieldType&quot;:11,&quot;DBDefault&quot;:10,&quot;SortNum&quot;:5,&quot;FieldDesc&quot;:&quot;表名&quot;,&quot;FieldLen&quot;:200,&quot;FieldDec&quot;:0,&quot;SNO&quot;:&quot;&quot;,&quot;SNO_NUM&quot;:&quot;&quot;,&quot;Regex&quot;:&quot;&quot;,&quot;IsPrimary&quot;:true,&quot;IsIdentity&quot;:false,&quot;IsNull&quot;:false,&quot;IsBllKey&quot;:true,&quot;IsIgnore&quot;:false,&quot;IsRequire&quot;:true,&quot;IsObsolete&quot;:false,&quot;IsSys&quot;:true,&quot;DefaultValue&quot;:&quot;&quot;,&quot;IsShow&quot;:true [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UpgradeVersion1054 {
            get {
                return ResourceManager.GetString("UpgradeVersion1054", resourceCulture);
            }
        }
    }
}
