//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiSql.DaMeng.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HiSql.DaMeng.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 DECLARE 
        ///  V_NUMBER INTEGER;
        ///   V_SECOUT INTEGER;
        ///BEGIN
        ///   
        ///   select count(*) into V_NUMBER from all_tables where table_name =&apos;Hi_TabModel&apos; and owner=&apos;[$Schema$]&apos;;
        ///   IF V_NUMBER = 0 THEN
        ///   EXECUTE IMMEDIATE  &apos;CREATE TABLE [$Schema$].Hi_TabModel(&apos;
        ///        || &apos;&quot;TabName&quot;  NVARCHAR2 (50) NOT NULL    ,&apos;
        /// || &apos;&quot;TabReName&quot;  NVARCHAR2 (50)   DEFAULT &apos;&apos;&apos;&apos;  ,&apos;
        /// || &apos;&quot;TabDescript&quot;  NVARCHAR2 (100)   DEFAULT &apos;&apos;&apos;&apos;  ,&apos;
        /// || &apos;&quot;TabStoreType&quot;  INTEGER    DEFAULT 0  ,&apos;
        /// || &apos;&quot;TabType&quot;  INTEGER    DEFAULT 0  ,&apos;
        /// | [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string HiSql {
            get {
                return ResourceManager.GetString("HiSql", resourceCulture);
            }
        }
    }
}
